# CREATION OF ARRAY USING NUMPY

In [1]:
#EXPERIMENT NO.05

In [3]:
#Aim: To perform operation Creation of Array using Numpy

In [1]:
#Name: KHUSHI AJAY MAGARDE
#Roll No: 14
#Class: CSE, 3B
#Subject:ET - 1
#Date: 02.08.2024

In [3]:
import numpy as np

In [9]:
k1=np.array([10,20,30,40,50,60,70,80])

In [7]:
k1

array([10, 20, 30, 40, 50, 60, 70, 80])

In [13]:
k2=np.array([[10,20,30,40],[60,70,80,90]])

In [15]:
k2

array([[10, 20, 30, 40],
       [60, 70, 80, 90]])

In [17]:
k3=np.array([['K1','K2'],['ABC','PQR'],[22,88]])

In [19]:
k3

array([['K1', 'K2'],
       ['ABC', 'PQR'],
       ['22', '88']], dtype='<U11')

In [29]:
k=('KHUSHI')

In [31]:
k

'KHUSHI'

In [33]:
type(k)

str

In [43]:
k[0]

'K'

In [49]:
k=np.arange(1,10)
k

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
k=np.arange(1,10,2)
k

array([1, 3, 5, 7, 9])

In [57]:
y=k*2
y

array([ 2,  6, 10, 14, 18])